jobs:
  include:
    - name: "Python 3 is EXPERIMENTAL"
      language: node_js
      node_js: "node"
      install:
        - pyenv global 3.7.1
        - python3.7 -m pip install --upgrade pip
        - make lint-py-build
      script:
        - NODE=$(which node) make lint lint-py
        - python3.7 ./configure.py
        - NODE=$(which node) make test

  allow_failures:
    - name: "Python 3 is EXPERIMENTAL"